# Generated by Django 4.2.1 on 2023-05-21 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bug', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='salary',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='person',
            name='phone',
            field=models.CharField(max_length=255),
        ),
    ]
